apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: RELATED_IMAGE_KONG
          value: registry.connect.redhat.com/kong/kong:2.8.1
        - name: RELATED_IMAGE_KONG_CONTROLLER
          value: registry.connect.redhat.com/kong/kong-ingress-controller:2.6.0-redhat
        - name: RELATED_IMAGE_CERTIFICATE_CONFIG
          value: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
