---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scc-manager-role
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot
  resources:
  - securitycontextconstraints
  verbs:
  - use
