apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default

patches:
- target:
    kind: Deployment
    name: controller-manager
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --enable-controller-controlplane
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --enable-controller-gateway
